System sensitivity study
intellistream/MorphStream pull request #86
Opened 2022-03-12 13:23 UTC by yancanmao

#84

2022-03-12 14:01 UTC, curryzjj submitted a review, later dismissed

2022-03-12 15:14 UTC, ShuhaoZhangTony requested changes
Where is the conflict come from??

2022-03-13 02:10 UTC, ShuhaoZhangTony commented
Haven't merged?

2022-03-13 02:40 UTC, yancanmao commented
It is because I did not merge the main to the coding branch, which causes massive conflicts among the two branches. However, the only difference that does not sync between the two branches is the README file. So I think the way to solve this problem is to rollback the main branch to the last commit i.e., before the last PR, and then I run a new PR to merge last motification to main.

2022-03-13 03:28 UTC, ShuhaoZhangTony approved these changes

2022-03-13 03:29 UTC, merged