Event detection app: finished preprocessing
intellistream/MorphStream pull request #92
Opened 2022-03-17 10:37 UTC by zhonghao-yang

Event detection application: 
- Finished tweet data preprocessing
- Finished word frequency calculation

TODO:
- Implement transactional frequency update
- Implement transactional clustering
- Implement event detection logic
- Improve the current word-elimination method in the pre-processing stage

2022-03-18 00:59 UTC, curryzjj commented on application/src/main/java/common/topology/transactional/initializer/EDInitializer.java
> +    }
具体的transactional operation应该是在Scheduler里实现，TableInitialize只是数据的加载和database的初始化

2022-03-18 01:03 UTC, curryzjj submitted a review, later dismissed
现在Toll Processing的处理流程应该还没更新，你们先参照着GrepSum来

2022-03-19 07:49 UTC, ShuhaoZhangTony requested changes
代码逻辑不对，需要修改。

2022-03-19 07:49 UTC, ShuhaoZhangTony commented on application/src/main/java/common/topology/transactional/EventDetection.java
> +                        builder.setBolt(LinearRoadConstants.Component.EXECUTOR, new TPBolt_nocc(0)//not available
名字都没换对？怎么还是TPXXX?

2022-03-19 07:49 UTC, ShuhaoZhangTony commented on application/src/main/java/common/topology/transactional/initializer/EDInitializer.java
> +    }
如jianjun指出的，具体执行逻辑不应该写在这里。参考一下其他应用的写法，refactor一下代码结构。

2022-03-19 07:52 UTC, zhonghao-yang commented on application/src/main/java/common/topology/transactional/initializer/EDInitializer.java
> +    }
好的老师，所有的问题我们都看了，之前有的部分是直接从Toll Processing拿过来的没有修改，周末我们会整理好

2022-08-30 14:21 UTC, ShuhaoZhangTony commented
Close this PR. Please PR the workable code to a branch called "StreamEventDetection".

2022-08-30 14:21 UTC, closed without merging